flip order and try directly calling api

diff --git a/.github/workflows/tag-major-version.yml b/.github/workflows/tag-major-version.yml
--- a/.github/workflows/tag-major-version.yml
+++ b/.github/workflows/tag-major-version.yml
@@ -36,25 +36,24 @@ jobs:
         # If tag doesn't exist locally, we still want to exit without failing
         run: git tag -d ${{ steps.version.outputs.major }} || true
 
-      - name: Delete old tag remotely
-        # https://docs.github.com/en/rest/git/refs?apiVersion=2022-11-28#delete-a-reference
-        # If tag doesn't exist remotely, we still want to exit without failing
-        uses: octokit/request-action@v2.x
-        with:
-          route:
-            DELETE /repos/${{ github.repository }}/git/refs/${{
-            steps.version.outputs.major }}
-          owner: ${{ github.repository_owner }}
-          repo: ${{ github.repository }}
-          conclusion: 'success'
-          status: 'completed'
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
       - name: Create new tag for major version
         run:
           git tag -a ${{ steps.version.outputs.major }} -m "Major version ${{
           steps.version.outputs.major }}"
+
+      - name: Delete old tag remotely
+        # https://docs.github.com/en/rest/git/refs?apiVersion=2022-11-28#delete-a-reference
+        # If tag doesn't exist remotely, we still want to exit without failing
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          curl \
+          -X DELETE \
+          -H "Accept: application/vnd.github+json" \
+          -H "Authorization: Bearer $GITHUB_TOKEN"\
+          -H "X-GitHub-Api-Version: 2022-11-28" \
+          https://api.github.com/repos/${{ github.repository }}/git/refs/${{
+            steps.version.outputs.major }} || true
 
       - name: Push new tag remotely
         run: git push -u origin ${{ steps.version.outputs.major }}
